;;; SPDX-FileCopyrightText: 2025-2026 Nikita Mitasov <me@ch4og.com>
;;; SPDX-License-Identifier: GPL-3.0-or-later

(define-module (aagl utils vars)
  #:use-module (guix build glib-or-gtk-build-system)
  #:use-module (nonguix multiarch-container)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages file)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages graphics)
  #:use-module (gnu packages gstreamer)
  #:use-module (gnu packages image)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages libunwind)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages sdl))

(define-public %gdk-pixbuf-loaders-cache-file-64
  (let ((real %gdk-pixbuf-loaders-cache-file))
    (if (string-prefix? "lib/" real)
        (string-append "lib64/" (substring real 4))
        real)))

(define-public %aagl-runtime-libs
  `(,@fhs-min-libs
    ("bash" ,bash)
    ("coreutils" ,coreutils)
    ("file" ,file)
    ("xz" ,xz)
    ("zenity" ,zenity)

    ("7zip" ,7zip)
    ("cabextract" ,cabextract)
    ("git" ,git)
    ("gnutls" ,gnutls)
    ("gst-libav" ,gst-libav)
    ("gst-plugins-bad" ,gst-plugins-bad)
    ("gst-plugins-good" ,gst-plugins-good)
    ("imagemagick" ,imagemagick)
    ("libunwind" ,libunwind)
    ("libwebp" ,libwebp)
    ("mangohud" ,mangohud)
    ("nss-certs" ,nss-certs)
    ("nss" ,nss)
    ("unzip" ,unzip)
    ("xdelta" ,xdelta)

    ("font-google-noto-emoji" ,font-google-noto-emoji)
    ("font-google-noto-sans-cjk" ,font-google-noto-sans-cjk)
    ("font-google-noto-serif-cjk" ,font-google-noto-serif-cjk)
    ("font-dejavu" ,font-dejavu)

    ("adwaita-icon-theme" ,adwaita-icon-theme)
    ("hicolor-icon-theme" ,hicolor-icon-theme)
    ("font-adwaita" ,font-adwaita)

    ("alsa-lib" ,alsa-lib)
    ("alsa-plugins:pulseaudio" ,alsa-plugins "pulseaudio")
    ("bzip2" ,bzip2)
    ("gcc:lib" ,gcc "lib")
    ("libadwaita" ,libadwaita)
    ("mesa" ,mesa)
    ("pulseaudio" ,pulseaudio)
    ("wayland" ,wayland)

    ("sdl2" ,sdl2)))
