;;; SPDX-FileCopyrightText: 2025 Nikita Mitasov <me@ch4og.com>
;;; SPDX-License-Identifier: GPL-3.0-or-later

(define-module (aagl lib fhsenv)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages file)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages graphics)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages image)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages libunwind)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages pciutils)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages video)
  #:use-module (gnu packages vulkan)
  #:use-module (gnu packages xorg)
  #:use-module (guix build-system copy)
  #:use-module (nongnu packages nvidia)
  #:use-module (nonguix multiarch-container)
  #:use-module (nonguix utils)
  #:export (aagl-container-for))

(define* (aagl-container-for pkg driver #:key (launcher-name (package-name pkg)))
  (nonguix-container
   (name launcher-name)
   (wrap-package pkg)
   (run (string-append "/bin/" launcher-name))

   (packages
    (modify-inputs %aagl-runtime-libs
		               (replace "mesa" driver)))

   (union32
    (fhs-union '()
               #:name "aagl-fhs-union-32"
               #:system "i686-linux"))

   (preserved-env %nvidia-environment-variable-regexps)

   (description
    (string-append launcher-name " running inside an FHS container"))))

(define %aagl-runtime-libs
  (append
   fhs-min-libs
   `(("bash" ,bash)
     ("glib" ,glib)
     ("gtk" ,gtk)
     ("libadwaita" ,libadwaita)
     ("pango" ,pango)
     ("cairo" ,cairo)
     ("gdk-pixbuf" ,gdk-pixbuf)
     ("vulkan-loader" ,vulkan-loader)
     ("vulkan-tools" ,vulkan-tools)
     ("mesa-utils" ,mesa-utils)
     ("gtk+" ,gtk+)
     ("gnome-themes-extra" ,gnome-themes-extra)
     ("gsettings-desktop-schemas" ,gsettings-desktop-schemas)
     ("adwaita-icon-theme" ,adwaita-icon-theme)
     ("hicolor-icon-theme" ,hicolor-icon-theme)
     ("font-dejavu" ,font-dejavu)
     ("font-liberation" ,font-liberation)
     ("libunwind" ,libunwind)
     ("imagemagick" ,imagemagick)
     ("cabextract" ,cabextract)
     ("coreutils" ,coreutils)
     ("nss" ,nss)
     ("nss-certs" ,nss-certs)
     ("gnutls" ,gnutls)
     ("xdelta" ,xdelta)
     ("curl" ,curl)
     ("openssl" ,openssl)
     ("sed" ,sed)
     ("grep" ,grep)
     ("tar" ,tar)
     ("xz" ,xz)
     ("bzip2" ,bzip2)
     ("git" ,git)
     ("p7zip" ,p7zip)
     ("libwebp" ,libwebp)
     ("wayland" ,wayland)
     ("alsa-lib" ,alsa-lib)
     ("alsa-plugins:pulseaudio" ,alsa-plugins "pulseaudio")
     ("pulseaudio" ,pulseaudio)
     ("pciutils" ,pciutils)
     ("udev" ,eudev)
     ("mesa" ,mesa)
     ("gcc:lib" ,gcc "lib")
     ("mangohud" ,mangohud))))
